oTable = $('#instancesTable').dataTable()
aPos = oTable.fnGetPosition( document.getElementById("instance_<%= @instance.id %>") )
oTable.fnDeleteRow(aPos)
oTable.fnDraw()
displayFlash('notice', 'Instance was successfully deleted.')