rvm:
  - "1.9.2"
bundler_args: --without production
before_script:
  - psql -c 'create database rpl_test;' -U postgres
  - "rake db:test:prepare"
script:
  - "rake test"
  - "rake spec"
  - "rake cucumber"