language: ruby
rvm:
  - 1.9.2
bundler_args: --without production
before_script:
  - psql -c 'create database rpl_test;' -U postgres
script:
  - RAILS_ENV=test bundle exec rake db:schema:load --trace
  - bundle exec rake test
  - bundle exec rake spec
  - bundle exec rake cucumber:ci