language: ruby
rvm:
  - 1.9.2
bundler_args: --without production
before_script:
  - psql -c 'create database rpl_test;' -U postgres
script:
  - RAILS_ENV=test bundle exec rake db:migrate --trace
  - bundle exec rake db:test:prepare
  - bundle exec rake