oTable = $('#commentsTable').dataTable()
aPos = oTable.fnGetPosition( document.getElementById("comment_<%= @comment.id %>") )
oTable.fnDeleteRow(aPos)
oTable.fnDraw()
displayFlash('notice', 'Comment was successfully deleted.')