oTable = $('#dataTable').dataTable()
aPos = oTable.fnGetPosition( document.getElementById("archetype_<%= @archetype.id %>") )
oTable.fnDeleteRow(aPos)
oTable.fnDraw()
displayFlash('notice', 'Archetype was successfully deleted.')