oTable = $('#dataTable').dataTable()
aPos = oTable.fnGetPosition( document.getElementById("link_<%= @link.id %>") )
oTable.fnDeleteRow(aPos)
oTable.fnDraw()
displayFlash('notice', 'Link was successfully deleted.')
