oTable = $('#playersTable').dataTable()
aPos = oTable.fnGetPosition( document.getElementById("player_<%= @player.id %>") )
oTable.fnDeleteRow(aPos)
oTable.fnDraw()
displayFlash('notice', 'Player was successfully deleted.')
