oTable = $('#characterTypesTable').dataTable()
aPos = oTable.fnGetPosition( document.getElementById("character_type_<%= @character_type.id %>") )
oTable.fnDeleteRow(aPos)
oTable.fnDraw()
displayFlash('notice', 'Character type was successfully deleted.')