oTable = $('#dataTable').dataTable()
aPos = oTable.fnGetPosition( document.getElementById("difficulty_<%= @difficulty.id %>") )
oTable.fnDeleteRow(aPos)
oTable.fnDraw()
displayFlash('notice', 'Difficulty was successfully deleted.')